name: New Relic Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install New Relic CLI
        run: |
          curl -Ls https://download.newrelic.com/install/newrelic-cli/scripts/install.sh | bash

      - name: Authenticate with New Relic
        run: newrelic login --apiKey ${{ secrets.NEW_RELIC_API_KEY }}

      - name: Apply Alert Policies
        run: ./scripts/update_alerts.sh

      - name: Apply Dashboards
        run: ./scripts/update_dashboards.sh
